### ISSUE TITLE
"nodename nor servname provided, or not known" for ActorSystem("multiprocTCPBase")

### ISSUE THREAD

**Issue by danielmitterdorfer** [godaddy/Thespian#16]
### Problem description

When creating an `ActorSystem("multiprocTCPBase")` I get: `socket.gaierror: [Errno 8] nodename nor servname provided, or not known`

Full trace:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/thespian/actors.py", line 465, in __init__
    systemBase, capabilities, logDefs)
  File "/usr/local/lib/python3.5/site-packages/thespian/actors.py", line 491, in _startupActorSys
    module = importlib.import_module('thespian.system.%s'%systemBase)
  File "/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/local/lib/python3.5/site-packages/thespian/system/multiprocTCPBase.py", line 16, in <module>
    from thespian.system.transport.TCPTransport import TCPTransport
  File "/usr/local/lib/python3.5/site-packages/thespian/system/transport/TCPTransport.py", line 88, in <module>
    from thespian.system.transport.IPBase import TCPv4ActorAddress
  File "/usr/local/lib/python3.5/site-packages/thespian/system/transport/IPBase.py", line 45, in <module>
    thisSystem = ThisSystem()
  File "/usr/local/lib/python3.5/site-packages/thespian/system/transport/IPBase.py", line 18, in __init__
    for usage in [0, socket.AI_PASSIVE]
  File "/usr/local/lib/python3.5/site-packages/thespian/system/transport/IPBase.py", line 20, in <listcomp>
    for rslt in socket.getaddrinfo(useAddr, 0, af, socktype, proto, usage)
  File "/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

### Steps to reproduce

1. `pip3 install thespian`
2. Run the following Python shell session:

```
dm@io:~ $ python3
Python 3.5.2 (default, Jun 29 2016, 13:43:58)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import thespian.actors
>>> thespian.actors.ActorSystem("multiprocTCPBase")
```

This produces the before-mentioned trace.

### Environment info

* thespian: 3.0.2
* OS: Darwin io 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64
* Python: Python 3.5.2

**Comment by kwquick** [comment]
Daniel,

This is typically caused by having an underspecified networking configuration: no specification of localhost or assignment of a hostname or domain.  Unfortunately, in the current implementation there is no way to know which one, so could you please provide the results of running the following:

```python
$ python3
>>> import socket
>>> hn = socket.gethostname()
>>> print(str(hn))
>>> fqdn = socket.getfqdn()
>>> print(str(fqdn))
>>> socket.getaddrinfo(None, 0, socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)
>>> socket.getaddrinfo(hn, 0, socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)
>>> socket.getaddrinfo(fqdn, 0, socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)
>>> exit()
$ grep localhost /etc/hosts
```

I will update the code to provide more information on failure of any of the above in the future, but the above information will help diagnose this.

**Comment by danielmitterdorfer** [comment]
Hi Kevin,

thanks for the hint. Here is the output of the shell session on my machine:

```bash
dm@io:~ $ python3
Python 3.5.2 (default, Jun 29 2016, 13:43:58)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> hn = socket.gethostname()
>>> print(str(hn))
io
>>> fqdn = socket.getfqdn()
>>> print(str(fqdn))
103.1.168.192.in-addr.arpa
>>> socket.getaddrinfo(None, 0, socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)
[(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('127.0.0.1', 0))]
>>> socket.getaddrinfo(hn, 0, socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)
[(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('192.168.1.103', 0))]
>>> socket.getaddrinfo(fqdn, 0, socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
>>>
dm@io:~ $ grep localhost /etc/hosts
# localhost is used to configure the loopback interface
127.0.0.1	localhost
::1             localhost
```

As you can see, the line `socket.getaddrinfo(fqdn, 0, socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)` seems to cause the problem that I have originally reported.

**Comment by kwquick** [comment]
Hi Daniel,

It looks like your fqdn is invalid, but that shouldn't necessarily be a fatal problem for Thespian.  I've pushed a commit to the Thespian repository that should just warn about this issue but attempt to continue.  Please let me know if this works for you.

**Comment by danielmitterdorfer** [comment]
Hi Kevin, thanks for your quick fix. This worked for me.

**Comment by danielmitterdorfer** [comment]
Hi Kevin, do you have any plans to cut a 3.0.3 release? [Rally](http://github.com/elastic/rally), is nearing its first release where we use Thespian internally and I'd be great to spare users this issue. :)

**Comment by kwquick** [comment]
Daniel, I should be able to get you a release sometime today.  -Kevin

**Comment by kwquick** [comment]
3.0.3 is released.

**Comment by danielmitterdorfer** [comment]
Many, many thanks Kevin for the quick release!

**Comment by danielmitterdorfer** [comment]
Well, this is embarrassing (on my part). I don't know how I was testing back then but unfortunately the issue is not fixed. I'll spare you further hassle and will create a PR very soon that really fixes the issue.

**Comment by kwquick** [comment]
Thespian 3.0.4 is released and contains the latest update.

**Comment by danielmitterdorfer** [comment]
I just tested it; 3.0.4 works perfectly. Thanks again Kevin.
