### ISSUE TITLE
Actor total creation error

### ISSUE THREAD

**Issue by R2D2-fwks** [godaddy/Thespian#48]
I am trying to create actors dynamically in for loop like this 
       
      `from thespian.actors import *
       from workers import *
       from database import Database as database
       db=database()
       class Cord(Actor):
            def receiveMessage(self, msg, sender):
                  if(msg == "Initiate"):
                     self.getProfileOfNode()
            elif(msg == "Got SomeThing to Proces"):
                  self.checkTheDataBasetoFindSomeWork(sender)

      def getProfileOfNode(self):
            profileData = db.getProfileInfo()
            print(profileData)
            NoOfWorkers = profileData["noOfworkers"]
            pingTimeOfWorker=profileData["pingTimeofWorkers"]
            messageSentToEveryWorker = {"message":"Start","interval":pingTimeOfWorker}
            print("Send to Create Pool Of actors")
            self.createPoolOfActors(NoOfWorkers,messageSentToEveryWorker)

      def createPoolOfActors(self,noofworkers,messageSentToEveryWorker):
            print("Inside the Creation of pool of Actors")
            for i in range(0,1):
                  print(i) #getting the result till here
                  nameofWorker = "Worker"+`i`
                  name = eval(nameofWorker)
                  nameofWorker = self.createActor(self,name) # sending error here
                  self.send(nameofWorker,messageSentToEveryWorker)`

Can you please help me the issue. 
The error which i am getting is this 
`2017-10-31 17:46:35,558 WARNING =>  Actor total creation error  [simpleSystemBase.py:482]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/thespian/system/simpleSystemBase.py", line 473, in _newRefAndActor
    .create(actorClass)
  File "/usr/local/lib/python2.7/dist-packages/thespian/system/utilis.py", line 319, in create
    return klass(**{ k: self.kwargs[k] for k in initsig if k in self.kwargs })
TypeError: 'Cord' object is not callable`

**Comment by kquick** [comment]
I don't think your problem is in the section of code that you pasted above, but in whatever is creating the initial Cord actor.  The location you marked with a comment above would have tried to create a "Worker0" or "Worker1" actor, but the error indicates it is the "Cord" actor having the failure.  It looks like you are passing an instance and not a class to the createActor... perhaps you have `ActorSystem().createActor(Cord())` instead of `ActorSystem().createActor(Cord)`?

A couple of other quick notes:
  * There is an indentation problem in the Cord class above: the elif is aligned with the `def receiveMessage` line... I assume this is a paste issue with the issue report.
  * You are creating a string (`nameofWorker`), then eval'ing that string to get a class, then calling `self.createActor` with self and the string.  You should not pass self as an actual argument, and you can specify the name as a string (although it will need to be a fully qualified lookup, so you might need `"__main__.Worker0"`, or `"ThisFile.Worker0"` where ThisFile is the module name of the file containing the Worker0 class definition.  Thus, replace:
```
              print(i) #getting the result till here
              nameofWorker = "Worker"+`i`
              name = eval(nameofWorker)
              nameofWorker = self.createActor(self,name) # sending error here
              self.send(nameofWorker,messageSentToEveryWorker)
```
with
```
              print(i) #getting the result till here
              nameofWorker = self.createActor('__main__.Worker' + str(i))
              self.send(nameofWorker, messageSentToEveryWorker)
```

**Comment by R2D2-fwks** [comment]
Thanks it helped me. Also one more thing i am using the system base class for the actor system , When i switch to multiPorcTCpBase. Again a lot of issues are coming .


`2017-11-02 11:54:54.394993 p13260 I    Admin registering with Convention @ ActorAddr-(T|:2000) (re-registering)
2017-11-02 11:54:54.396665 p13260 I    Setting log aggregator of ActorAddr-(T|:42167) to ActorAddr-(T|:2000)
2017-11-02 11:54:54.398027 p14404 I    Got Convention registration from ActorAddr-(T|:1900) (re-registering) (new? False)
2017-11-02 11:54:54.400797 p13260 I    Got Convention registration from ActorAddr-(T|:2000) (re-registering) (new? False)
2017-11-02 11:57:00.948845 p13260 I    Pending Actor request received for __main__.RootNode reqs None from ActorAddr-(T|:45052)
2017-11-02 11:57:00.951404 p20439 I    Starting Actor __main__.RootNode at ActorAddr-(T|:33749) (parent ActorAddr-(T|:1900), admin ActorAddr-(T|:1900), srcHash None)
2017-11-02 11:57:00.957805 p20440 I    Starting Actor pinger.Pinger at ActorAddr-(T|:42550) (parent ActorAddr-(T|:33749), admin ActorAddr-(T|:1900), srcHash None)
2017-11-02 11:57:00.959707 p20441 I    Starting Actor cordinating.Cord at ActorAddr-(T|:40905) (parent ActorAddr-(T|:33749), admin ActorAddr-(T|:1900), srcHash None)
2017-11-02 11:57:00.961708 p20441 I    Handling exception on msg "Initiate": [Errno 32] Broken pipe
2017-11-02 11:57:00.961963 p20441 Warn Actor cordinating.Cord @ ActorAddr-(T|:40905) retryable exception on message Initiate: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/thespian/system/actorManager.py", line 153, in _handleOneMessage
    actor_result = self.actorInst.receiveMessage(msg, envelope.sender)
  File "/home/vinoo/work/practice/python/thespian/cordinating.py", line 9, in receiveMessage
    signal(SIGPIPE , SIG_DFL)
  File "/home/vinoo/work/practice/python/thespian/cordinating.py", line 14, in getProfileOfNode
    self.checkTheDataBasetoFindSomeWork(sender)
  File "/home/vinoo/work/practice/python/thespian/database.py", line 12, in getProfileInfo
    def getProfileInfo(self):
IOError: [Errno 32] Broken pipe

2017-11-02 11:57:00.962501 p20441 I    Actor cordinating.Cord @ ActorAddr-(T|:40905) second exception on message Initiate: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/thespian/system/actorManager.py", line 168, in _handleOneMessage
    actor_result = self.actorInst.receiveMessage(copy.deepcopy(msg), envelope.sender)
  File "/home/vinoo/work/practice/python/thespian/cordinating.py", line 9, in receiveMessage
    signal(SIGPIPE , SIG_DFL)
  File "/home/vinoo/work/practice/python/thespian/cordinating.py", line 14, in getProfileOfNode
    self.checkTheDataBasetoFindSomeWork(sender)
  File "/home/vinoo/work/practice/python/thespian/database.py", line 12, in getProfileInfo
    def getProfileInfo(self):
IOError: [Errno 32] Broken pipe``

**Comment by R2D2-fwks** [comment]
Thanks for the comment , my issue got solved .

**Comment by R2D2-fwks** [comment]
Hi @kquick , 
one last thing i just want to understand as i am creating actors on the fly is it good to use the methoodlogy what you suggested  `nameofWorker = self.createActor('__main__.Worker' + str(i))`
 can i use the global name of the actors

**Comment by kquick** [comment]
When you create an actor, the first argument should be the class name of the target class, either as the Class itself or the string name of the class (if you are specifying the string name, use right import qualifications):

foo/bar.py:
```
class ElephantActor(Actor): ...
```

main.py:
```
import foo.bar
ActorSystem().createActor(foo.bar.ElephantActor)
ActorSystem().createActor("foo.bar.ElephantActor")
```
both of the createActor calls will work and create (two different) ElephantActor instances.  I used the string form in my original example because it looked like you were constructing the name of the type of Actor you were creating dynamically.

The `globalName` parameter is an additional parameter that can be specified as a string only to associate that string name with a single, global (singleton) instance of that Actor.  The Actor is created if it does not already exist at that name.

```
a = ActorSystem.createActor(foo.bar.ElephantActor, globalName='elephant')
b = ActorSystem.createActor(foo.bar.ElephantActor, globalName='elephant')
c = ActorSystem.createActor(foo.bar.ElephantActor)
d = ActorSystem.createActor(foo.bar.ElephantActor, globalName='elephant')
e = ActorSystem.createActor(foo.bar.ElephantActor, globalName='harry')

assert a == b
assert a != c
assert a == d
assert a != e
assert c != e
```

For more information, see http://thespianpy.com/doc/using.html#hH-a565af1b-aabb-4336-a51d-7505c072c319 or http://thespianpy.com/doc/using.html#hH-3663d87d-8a2f-485b-aeef-c6e9cf418b4c and also http://thespianpy.com/doc/using.html#hH-2d5ef9c7-2132-45f9-b6eb-6f2729f5b232.
